import { log } from 'lognow'
import { mkdir, writeFile } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { version } from '../../package.json'
import { readFileSafe } from './utilities'

const CONFIG_TYPES_FILE_NAME = 'itson.d.ts'

async function getConfigTypesSource(): Promise<string> {
	// The bundled CLI ships the definitions alongside dist/cli.js, when running
	// from source (e.g. tests) they're in src/assets
	const candidates = [
		new URL(CONFIG_TYPES_FILE_NAME, import.meta.url),
		new URL(`../assets/${CONFIG_TYPES_FILE_NAME}`, import.meta.url),
	]

	for (const candidate of candidates) {
		const content = await readFileSafe(fileURLToPath(candidate))
		if (content !== undefined) {
			return content
		}
	}

	throw new Error(
		`Could not find bundled ${CONFIG_TYPES_FILE_NAME}. Try reinstalling itson, or file an issue.`,
	)
}

/**
 * Write the itson config type definitions to `<directory>/itson.d.ts` so config
 * files can reference them with a stable home-relative import: `satisfies
 * import('./.itson/itson.js').ItsonConfig`.
 *
 * The write is idempotent, and refreshes stale definitions from older itson
 * versions.
 *
 * @returns The path to the type definition file.
 */
export async function dumpConfigTypes(
	directory: string = path.join(os.homedir(), '.itson'),
): Promise<string> {
	const source = await getConfigTypesSource()
	const content = `// Generated by itson v${version}. Do not edit; itson refreshes this file each time it runs.\n\n${source}`
	const destination = path.join(directory, CONFIG_TYPES_FILE_NAME)

	const existingContent = await readFileSafe(destination)
	if (existingContent === content) {
		log.debug(`Config types already up to date at ${destination}`)
		return destination
	}

	await mkdir(directory, { recursive: true })
	await writeFile(destination, content, 'utf8')
	log.debug(`Wrote config types to ${destination}`)
	return destination
}
