// @case-police-ignore MacOS

import { readFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { describe, expect, expectTypeOf, it } from 'vitest'
import type { ItsonConfig as ItsonConfigAuthoring } from '../src/assets/itson'
import type { ItsonConfigInput } from '../src/lib/config'
import { itsonConfigSchema } from '../src/lib/config'
import { dumpConfigTypes } from '../src/lib/config-types'

const ARTIFACT_PATTERN_REGEX = /^AllWork[\-.]Bundle.+\.zip$/v

describe('config authoring types', () => {
	it('should stay in sync with the zod schema', () => {
		// Compile-time guards: a drift between src/assets/itson.d.ts and the
		// schema in src/lib/config.ts fails type checking
		expectTypeOf<ItsonConfigInput>().toExtend<ItsonConfigAuthoring>()
		expectTypeOf<ItsonConfigAuthoring>().toExtend<ItsonConfigInput>()

		expect(itsonConfigSchema).toBeDefined()
	})

	it('should accept a realistic config in authoring form', () => {
		const example = {
			applications: [
				{
					name: 'AllWork',
					command: '/Applications/AllWork.app/Contents/MacOS/AllWork',
					arguments: ['--config=/Users/user/Applications/AllWork/settings.json'],
					logUpload: {
						bucketName: 'logs',
						endpoint: 'https://example.r2.cloudflarestorage.com/',
						ignorePatterns: ['*.log'],
						localPath: '/Users/user/Library/Logs/AllWork',
						remotePath: 'all-work',
						type: 's3',
					},
					update: {
						artifactPattern: ARTIFACT_PATTERN_REGEX,
						destination: '/Applications/AllWork.app',
						owner: 'kitschpatrol',
						repo: 'allwork',
						type: 'github',
					},
				},
				{
					name: 'Interpose',
					command: 'interpose',
					update: { owner: 'kitschpatrol', repo: 'interpose', type: 'github-python' },
				},
			],
			runOnStartup: true,
			tasks: [
				{
					name: 'Reboot Cameras',
					command: '/opt/homebrew/bin/python3',
					arguments: ['/Users/user/Applications/reboot_cameras.py'],
					schedule: '0 1 * * *',
				},
			],
		} satisfies ItsonConfigAuthoring

		const parsed = itsonConfigSchema.parse(example)

		expect(parsed.offline).toBe(false)
		expect(parsed.runOnStartup).toBe(true)
		expect(parsed.applications).toHaveLength(2)
		expect(parsed.tasks).toHaveLength(1)

		const update = parsed.applications[0]?.update
		if (update?.type !== 'github') {
			throw new Error('Expected a github update strategy')
		}

		expect(update.artifactPattern).toBeInstanceOf(RegExp)
		expect(update.artifactPattern.test('AllWork-Bundle-1.0.0.zip')).toBe(true)
	})
})

describe('dumpConfigTypes', () => {
	it('should write the type definitions and be idempotent', async () => {
		const directory = join(
			tmpdir(),
			`itson-config-types-${Date.now()}-${Math.random().toString(36).slice(2)}`,
		)

		const typesPath = await dumpConfigTypes(directory)
		const content = await readFile(typesPath, 'utf8')

		expect(typesPath).toBe(join(directory, 'itson.d.ts'))
		expect(content).toContain('Generated by itson v')
		expect(content).toContain('export type ItsonConfig')
		expect(content).toContain('export type RegexPattern')

		// Rewriting identical content should be a no-op that resolves to the same path
		const secondPath = await dumpConfigTypes(directory)
		expect(secondPath).toBe(typesPath)
		expect(await readFile(secondPath, 'utf8')).toBe(content)
	})
})
